const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');

class ExportService {
    
    // ============================================
    // PDF EXPORT (Corporate Enterprise Styling)
    // ============================================
    async generatePDF(res, reportTitle, startDate, endDate, stats, rows) {
        const doc = new PDFDocument({ margin: 40, size: 'A4' });
        
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="${reportTitle.replace(/\s+/g, '_')}.pdf"`);
        doc.pipe(res);

        // Corporate Header Background
        doc.rect(0, 0, 595, 100).fill('#1E3A8A'); // Indigo Blue Corporate Header
        
        // Logo Placeholder
        doc.rect(40, 20, 60, 60).fill('#FFFFFF');
        doc.fillColor('#1E3A8A').fontSize(14).font('Helvetica-Bold').text('LOGO', 50, 45);

        // Header Text
        doc.fillColor('#FFFFFF').fontSize(24).font('Helvetica-Bold').text('ENTERPRISE ATTENDANCE', 120, 30);
        doc.fontSize(12).font('Helvetica').text(reportTitle, 120, 60);
        doc.text(`${startDate} to ${endDate}`, 120, 75);

        doc.moveDown(4);

        // Statistics Cards (Visual UI in PDF)
        const statBoxY = 120;
        doc.roundedRect(40, statBoxY, 120, 50, 5).fill('#F3F4F6');
        doc.fillColor('#374151').fontSize(10).text('TOTAL STUDENTS', 50, statBoxY + 10);
        doc.fillColor('#111827').fontSize(16).font('Helvetica-Bold').text(stats.totalStudents.toString(), 50, statBoxY + 25);

        doc.roundedRect(170, statBoxY, 120, 50, 5).fill('#F0FDF4');
        doc.fillColor('#166534').fontSize(10).text('PRESENT', 180, statBoxY + 10);
        doc.fillColor('#15803D').fontSize(16).font('Helvetica-Bold').text(stats.present.toString(), 180, statBoxY + 25);

        doc.roundedRect(300, statBoxY, 120, 50, 5).fill('#FEF2F2');
        doc.fillColor('#991B1B').fontSize(10).text('ABSENT', 310, statBoxY + 10);
        doc.fillColor('#B91C1C').fontSize(16).font('Helvetica-Bold').text(stats.absent.toString(), 310, statBoxY + 25);

        doc.roundedRect(430, statBoxY, 120, 50, 5).fill('#EFF6FF');
        doc.fillColor('#1E40AF').fontSize(10).text('ATTENDANCE %', 440, statBoxY + 10);
        doc.fillColor('#1D4ED8').fontSize(16).font('Helvetica-Bold').text(`${stats.percentage}%`, 440, statBoxY + 25);

        doc.y = statBoxY + 70;

        // Table Header
        const tableTop = doc.y;
        const col = { name: 40, date: 150, checkIn: 220, checkOut: 290, status: 360, face: 420, gps: 480 };

        doc.rect(38, tableTop - 5, 515, 20).fill('#1E3A8A');
        doc.fontSize(9).font('Helvetica-Bold').fillColor('#FFFFFF');
        doc.text('Student Name', col.name, tableTop);
        doc.text('Date', col.date, tableTop);
        doc.text('Check-In', col.checkIn, tableTop);
        doc.text('Check-Out', col.checkOut, tableTop);
        doc.text('Status', col.status, tableTop);
        doc.text('Face Valid', col.face, tableTop);
        doc.text('GPS Valid', col.gps, tableTop);

        doc.y += 20;

        // Table Rows
        doc.font('Helvetica').fontSize(8);

        if (rows.length === 0) {
            doc.fillColor('#666666').text('No attendance records found for this period.', col.name, doc.y + 10);
        } else {
            rows.forEach((row, i) => {
                if (doc.y > 750) {
                    doc.addPage();
                    doc.y = 40; // Reset Y on new page
                }

                if (i % 2 === 0) doc.rect(38, doc.y - 2, 515, 16).fill('#F9FAFB');
                
                const rowY = doc.y;
                doc.fillColor('#111827').text(row.studentName || 'Unknown', col.name, rowY, { width: 100 });
                doc.fillColor('#4B5563').text(row.date || '--', col.date, rowY);
                doc.text(row.checkInTime || '--:--', col.checkIn, rowY);
                doc.text(row.checkOutTime || '--:--', col.checkOut, rowY);
                
                // Status colors
                if (row.status === 'Present') doc.fillColor('#15803D');
                else doc.fillColor('#B91C1C');
                doc.text(row.status || 'Absent', col.status, rowY);

                // Face & GPS colors
                doc.fillColor(row.faceStatus === 'Verified' ? '#15803D' : '#B91C1C').text(row.faceStatus || 'Failed', col.face, rowY);
                doc.fillColor(row.gpsStatus === 'Verified' ? '#15803D' : '#B91C1C').text(row.gpsStatus || 'Failed', col.gps, rowY);

                doc.moveDown(0.8);
            });
        }

        // Footer
        doc.moveDown(2);
        doc.fontSize(8).fillColor('#9CA3AF').text('Generated by Enterprise Smart Attendance System © ' + new Date().getFullYear(), { align: 'center' });

        doc.end();
    }

    // ============================================
    // EXCEL EXPORT (Corporate Formatting)
    // ============================================
    async generateExcel(res, reportTitle, startDate, endDate, stats, rows) {
        const workbook = new ExcelJS.Workbook();
        workbook.creator = 'Enterprise Smart Attendance System';
        workbook.created = new Date();

        const sheet = workbook.addWorksheet('Attendance Report', { views: [{ showGridLines: false }] });

        // Corporate Title Row
        sheet.mergeCells('A1:G2');
        const titleCell = sheet.getCell('A1');
        titleCell.value = `ENTERPRISE REPORT: ${reportTitle.toUpperCase()}`;
        titleCell.font = { size: 18, bold: true, color: { argb: 'FFFFFFFF' } };
        titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A8A' } };
        titleCell.alignment = { horizontal: 'center', vertical: 'middle' };

        // Stats Row
        sheet.mergeCells('A3:G3');
        const statsCell = sheet.getCell('A3');
        statsCell.value = `Period: ${startDate} to ${endDate}   |   Total: ${stats.totalStudents}   |   Present: ${stats.present}   |   Absent: ${stats.absent}   |   Attendance: ${stats.percentage}%`;
        statsCell.font = { size: 10, bold: true, color: { argb: 'FF111827' } };
        statsCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } };
        statsCell.alignment = { horizontal: 'center' };

        sheet.addRow([]);

        // Columns Definition
        sheet.columns = [
            { key: 'studentCode', width: 15 },
            { key: 'studentName', width: 30 },
            { key: 'date', width: 15 },
            { key: 'checkInTime', width: 15 },
            { key: 'checkOutTime', width: 15 },
            { key: 'status', width: 15 },
            { key: 'faceStatus', width: 15 },
            { key: 'gpsStatus', width: 15 }
        ];

        // Headers
        const headerRow = sheet.addRow(['Student ID', 'Student Name', 'Date', 'Check In', 'Check Out', 'Status', 'Face Valid', 'GPS Valid']);
        headerRow.height = 25;
        headerRow.eachCell((cell) => {
            cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF374151' } };
            cell.alignment = { vertical: 'middle', horizontal: 'center' };
            cell.border = { bottom: { style: 'medium', color: { argb: 'FF111827' } } };
        });

        // Rows
        rows.forEach((row, i) => {
            const dataRow = sheet.addRow([
                row.studentCode || '',
                row.studentName || 'Unknown',
                row.date || '',
                row.checkInTime || '--:--',
                row.checkOutTime || '--:--',
                row.status || 'Absent',
                row.faceStatus || 'Failed',
                row.gpsStatus || 'Failed'
            ]);

            // Styling based on Status
            const statusCell = dataRow.getCell(6);
            if (row.status === 'Present') statusCell.font = { color: { argb: 'FF15803D' }, bold: true };
            else statusCell.font = { color: { argb: 'FFB91C1C' }, bold: true };

            const faceCell = dataRow.getCell(7);
            if (row.faceStatus === 'Verified') faceCell.font = { color: { argb: 'FF15803D' } };
            else faceCell.font = { color: { argb: 'FFB91C1C' } };

            const gpsCell = dataRow.getCell(8);
            if (row.gpsStatus === 'Verified') gpsCell.font = { color: { argb: 'FF15803D' } };
            else gpsCell.font = { color: { argb: 'FFB91C1C' } };

            // Zebra Striping
            if (i % 2 === 0) {
                dataRow.eachCell((cell) => {
                    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
                });
            }
        });

        sheet.autoFilter = { from: 'A5', to: `H${5 + rows.length}` };

        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader('Content-Disposition', `attachment; filename="${reportTitle.replace(/\s+/g, '_')}.xlsx"`);
        await workbook.xlsx.write(res);
        res.end();
    }

    // ============================================
    // CSV EXPORT (New Feature)
    // ============================================
    async generateCSV(res, reportTitle, startDate, endDate, rows) {
        res.setHeader('Content-Type', 'text/csv');
        res.setHeader('Content-Disposition', `attachment; filename="${reportTitle.replace(/\s+/g, '_')}.csv"`);
        
        // Write CSV Header
        res.write('Student ID,Student Name,Date,Check In,Check Out,Status,Face Verified,GPS Verified\n');
        
        // Write Rows
        rows.forEach(row => {
            const rowData = [
                row.studentCode || '',
                `"${row.studentName || 'Unknown'}"`,
                row.date || '',
                row.checkInTime || '',
                row.checkOutTime || '',
                row.status || 'Absent',
                row.faceStatus || 'Failed',
                row.gpsStatus || 'Failed'
            ].join(',');
            res.write(rowData + '\n');
        });
        
        res.end();
    }
}

module.exports = new ExportService();
